# Site settings
title: i9life | Revendedor Oficial
description: "i9 sua vida, realize seus sonhos."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain

# Hero
hero: 
    hero_img: hero.png
    hero_title: i9Life | Revendedor Oficial
    hero_description: i9 sua vida, realize seus sonhos, seja um revendedor.

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: (44) 9882-5411
    email: contato@andersonsouza.net
    address: Colorado Paraná

# Opening hours
monday_friday: 9:00 – 18:00
saturday: 10:00 – 17:00
sunday: 10:00 – 15:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: São Paulo, Brasil
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype: skype:obaez_design?userinfo
feed: yes

# Footer
copyright: © 2016 i9life | Revendedor Oficial

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
